
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Transfer.Models
{

using System;
    using System.Collections.Generic;
    
public partial class toIT
{

    public int 識別碼 { get; set; }

    public string SecurityName { get; set; }

    public string PriceSymbol { get; set; }

    public string IM_Name { get; set; }

    public string Issuer { get; set; }

    public string SMF { get; set; }

    public Nullable<System.DateTime> IssueDate { get; set; }

    public Nullable<System.DateTime> MaturityDate { get; set; }

    public string Currency { get; set; }

    public Nullable<System.DateTime> C1stCouponDate { get; set; }

    public string LastCouponType { get; set; }

    public string PaymentType { get; set; }

    public Nullable<short> CouponFrequency { get; set; }

    public Nullable<short> RefixFrequency { get; set; }

    public string DayCountConvention { get; set; }

    public Nullable<double> CouponRate { get; set; }

    public Nullable<double> RedemptionValue { get; set; }

    public Nullable<System.DateTime> C1stCallDate { get; set; }

    public string Sinkble { get; set; }

    public Nullable<double> FloatingSpread { get; set; }

    public string ResetIndex { get; set; }

}

}
