
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Transfer.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Econ_D_Var_Lag_C13_2019
{

    public string Year_Quartly { get; set; }

    public Nullable<double> Consumer_Price_Index_L2 { get; set; }

    public Nullable<double> Unemployment_Rate_L2 { get; set; }

}

}
