
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Transfer.Models
{

using System;
    using System.Collections.Generic;
    
public partial class IFRS9_Impaire_Override
{

    public string Reference_Nbr { get; set; }

    public Nullable<System.DateTime> Processing_Date { get; set; }

    public Nullable<double> Override_El { get; set; }

    public string Override_note { get; set; }

    public string Product_Code { get; set; }

    public string Override_User { get; set; }

    public string Audit_User { get; set; }

}

}
