
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Transfer.Models
{

using System;
    using System.Collections.Generic;
    
public partial class IFRS9_Bond_Report
{

    public string PRJID { get; set; }

    public string FLOWID { get; set; }

    public string Report_Date { get; set; }

    public string Processing_Date { get; set; }

    public string Product_Code { get; set; }

    public string Reference_Nbr { get; set; }

    public Nullable<double> PD { get; set; }

    public Nullable<double> Lifetime_EL { get; set; }

    public Nullable<double> Y1_EL { get; set; }

    public Nullable<double> EL { get; set; }

    public string Impairment_Stage { get; set; }

    public int Version { get; set; }

    public Nullable<double> Principal { get; set; }

    public Nullable<double> Ori_Amount { get; set; }

    public Nullable<double> Interest_Receivable { get; set; }

    public Nullable<double> Amort_Amt_Ori_Tw { get; set; }

    public Nullable<double> Amort_Amt_Tw { get; set; }

    public Nullable<double> Ex_rate { get; set; }

    public Nullable<double> Ori_Ex_rate { get; set; }

    public Nullable<double> Lifetime_EL_Ex { get; set; }

    public Nullable<double> Y1_EL_Ex { get; set; }

    public Nullable<double> EL_Ex { get; set; }

    public Nullable<double> Principal_EL_Ex { get; set; }

    public Nullable<double> Interest_Receivable_EL_Ex { get; set; }

    public Nullable<double> Lifetime_EL_Ori_Ex { get; set; }

    public Nullable<double> Y1_EL_Ori_Ex { get; set; }

    public Nullable<double> EL_Ori_Ex { get; set; }

    public Nullable<double> Principal_EL_Ori_Ex { get; set; }

    public Nullable<double> Interest_Receivable_EL_Ori_Ex { get; set; }

    public string ISSUER { get; set; }

    public string Bond_Number { get; set; }

    public string Lots { get; set; }

    public string Security_Name { get; set; }

    public string Segment_Name { get; set; }

    public Nullable<System.DateTime> Origination_Date { get; set; }

    public Nullable<System.DateTime> Maturity_Date { get; set; }

    public string ISSUER_AREA { get; set; }

    public string Industry_Sector { get; set; }

    public string IAS39_CATEGORY { get; set; }

    public string Bond_Aera { get; set; }

    public string Asset_Type { get; set; }

    public string Currency_Code { get; set; }

    public string ASSET_SEG { get; set; }

    public string IH_OS { get; set; }

    public string Portfolio { get; set; }

    public string PRODUCT { get; set; }

    public Nullable<double> Market_Value_Ori { get; set; }

    public Nullable<double> Market_Value_TW { get; set; }

    public Nullable<double> Current_Int_Rate { get; set; }

    public Nullable<double> EIR { get; set; }

    public string Lien_position { get; set; }

    public string Principal_Payment_Method_Code { get; set; }

    public Nullable<double> Current_LGD { get; set; }

    public Nullable<double> Exposure { get; set; }

    public string Original_External_Rating { get; set; }

    public string Current_External_Rating { get; set; }

    public string Portfolio_Name { get; set; }

    public Nullable<double> Value_Change_Ratio { get; set; }

    public Nullable<int> Accumulation_Loss_last_Month { get; set; }

    public Nullable<int> Accumulation_Loss_This_Month { get; set; }

    public string Watch_IND { get; set; }

    public string Map_Rule_Id_D70 { get; set; }

    public string Warning_IND { get; set; }

    public string Map_Rule_Id_D71 { get; set; }

    public Nullable<double> Ori_Amount_Ori_Ex { get; set; }

    public Nullable<double> Principal_EL_Ori { get; set; }

    public Nullable<double> Interest_Receivable_EL_Ori { get; set; }

    public Nullable<double> Interest_Receivable_Tw { get; set; }

    public Nullable<double> Principal_Diff_Tw { get; set; }

    public string ISIN_Changed_Ind { get; set; }

    public string Bond_Number_Old { get; set; }

    public string Lots_Old { get; set; }

    public string Portfolio_Name_Old { get; set; }

    public Nullable<System.DateTime> Origination_Date_Old { get; set; }

    public string Create_User { get; set; }

    public Nullable<System.DateTime> Create_Date { get; set; }

    public Nullable<System.TimeSpan> Create_Time { get; set; }

    public string LastUpdate_User { get; set; }

    public Nullable<System.DateTime> LastUpdate_Date { get; set; }

    public Nullable<System.TimeSpan> LastUpdate_Time { get; set; }

    public Nullable<double> EL_EX_Diff { get; set; }

    public Nullable<double> LGD_Int { get; set; }

    public Nullable<double> PD_Int { get; set; }

    public Nullable<double> Ori_Ex_rate_to_USD { get; set; }

    public Nullable<double> Ex_rate_to_USD { get; set; }

    public string Trading_Number { get; set; }

}

}
