
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Transfer.Models
{

using System;
    using System.Collections.Generic;
    
public partial class IFRS9_SFTP_Log
{

    public int Id { get; set; }

    public string Transfer_Type { get; set; }

    public Nullable<System.DateTime> Report_Date { get; set; }

    public Nullable<System.DateTime> Start_Time { get; set; }

    public Nullable<System.DateTime> End_Time { get; set; }

    public Nullable<bool> Flag { get; set; }

}

}
